### ISSUE TITLE
Problems with Python2 install pip

### ISSUE THREAD

**Issue by mnoskoski** [mnoskoski/scripts-template-python#1]
Problem: 

Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmp2aZyDl/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")

In my Dockerfike:
**RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py**

**Comment by mnoskoski** [comment]
I change the URL in my Dockerfile  to new URL download pip and resolve.




RUN curl "https://bootstrap.pypa.io/2.7/get-pip.py" -o "get-pip.py"
RUN python get-pip.py
